"""Qdrant cognitive memory store — async embedding + vector storage.

Hooks into the runtime via try/except ImportError pattern.
Embeddings are generated by nomic-embed-text-v1.5 on RX9070.
"""

import json
import time
import uuid
from pathlib import Path
from typing import Any

try:
    import requests as _req
    _HAVE_REQUESTS = True
except ImportError:
    _HAVE_REQUESTS = False

# ── config (overridable via env) ──────────────────────────────────────
QDRANT_HOST = "http://127.0.0.1:6333"
LM_STUDIO_EMBED_URL = "http://192.168.1.50:1234/v1/embeddings"
EMBED_MODEL = "text-embedding-nomic-embed-text-v1.5"
EMBED_BATCH_SIZE = 10
EMBED_TIMEOUT = 5

# ── helpers ───────────────────────────────────────────────────────────

def _text_for_embedding(payload: dict) -> str:
    """Build a flat text string from a payload for embedding.

    Joins key fields into a single searchable sentence.
    """
    parts = []
    for key in ("event_type", "message", "task_type", "model", "node", "host"):
        val = payload.get(key)
        if val:
            parts.append(str(val))
    return " | ".join(parts) if parts else json.dumps(payload, ensure_ascii=False)


def _collection_path(name: str) -> Path:
    return Path(f"/opt/ai-lab/runtime/state/qdrant_{name}.jsonl")


# ── embedding ─────────────────────────────────────────────────────────

def get_embedding(text: str) -> list[float] | None:
    """Generate embedding via LM Studio nomic-embed-text-v1.5."""
    if not _HAVE_REQUESTS:
        return None
    try:
        resp = _req.post(
            LM_STUDIO_EMBED_URL,
            json={"model": EMBED_MODEL, "input": text},
            timeout=EMBED_TIMEOUT,
        )
        if resp.status_code == 200:
            data = resp.json()
            return data["data"][0]["embedding"]
    except Exception:
        pass
    return None


def get_embeddings_batch(texts: list[str]) -> list[list[float]] | None:
    """Generate embeddings for a batch of texts."""
    if not _HAVE_REQUESTS:
        return None
    if not texts:
        return []
    try:
        batch = texts[:EMBED_BATCH_SIZE]
        resp = _req.post(
            LM_STUDIO_EMBED_URL,
            json={"model": EMBED_MODEL, "input": batch},
            timeout=EMBED_TIMEOUT,
        )
        if resp.status_code == 200:
            data = resp.json()
            return [item["embedding"] for item in data["data"]]
    except Exception:
        pass
    return None


# ── Qdrant REST helpers ──────────────────────────────────────────────

def _qdrant_get(path: str) -> dict | None:
    if not _HAVE_REQUESTS:
        return None
    try:
        resp = _req.get(f"{QDRANT_HOST}{path}", timeout=3)
        if resp.status_code in (200, 201):
            return resp.json()
    except Exception:
        pass
    return None


def _qdrant_put(path: str, body: dict) -> dict | None:
    if not _HAVE_REQUESTS:
        return None
    try:
        resp = _req.put(f"{QDRANT_HOST}{path}", json=body, timeout=5)
        if resp.status_code in (200, 201):
            return resp.json()
    except Exception:
        pass
    return None


# ── collection management ────────────────────────────────────────────

COLLECTION_CONFIGS: dict[str, dict] = {
    "routing_history": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": 90,
    },
    "cognitive_history": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": 90,
    },
    "optimizer_history": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": 180,
    },
    "incidents": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": None,  # unlimited
    },
    "runtime_snapshots": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": 30,
    },
    "working_memory": {
        "vectors": {"size": 768, "distance": "Cosine"},
        "retention_days": 7,
    },
}


def ensure_collections() -> None:
    """Create Qdrant collections if they don't exist."""
    if not _HAVE_REQUESTS:
        return
    existing = _qdrant_get("/collections")
    if not existing:
        return
    existing_names = {c["name"] for c in existing.get("result", {}).get("collections", [])}

    for name, cfg in COLLECTION_CONFIGS.items():
        if name in existing_names:
            continue
        body = {
            "vectors": cfg["vectors"],
            "optimizers_config": {"default_segment_number": 2},
        }
        _qdrant_put(f"/collections/{name}", body)


# ── store ─────────────────────────────────────────────────────────────

def store_event(collection: str, payload: dict, embedding: list[float] | None = None) -> bool:
    """Store an event in Qdrant + JSONL backup.

    Returns True on success (Qdrant or JSONL-only fallback).
    """
    point_id = str(uuid.uuid4())
    point = {
        "id": point_id,
        "payload": payload,
    }
    if embedding:
        point["vector"] = embedding

    # Always write to JSONL backup (source of truth)
    try:
        jl_path = _collection_path(collection)
        jl_path.parent.mkdir(parents=True, exist_ok=True)
        with open(jl_path, "a") as f:
            f.write(json.dumps({"id": point_id, "payload": payload, "timestamp": time.time()}, ensure_ascii=False) + "\n")
    except Exception:
        pass

    # Upsert to Qdrant
    if not _HAVE_REQUESTS:
        return True
    try:
        body = {"points": [point]}
        _qdrant_put(f"/collections/{collection}/points", body)
    except Exception:
        pass
    return True


def store_embedding(collection: str, payload: dict) -> bool:
    """Generate embedding from payload text and store in Qdrant."""
    text = _text_for_embedding(payload)
    embedding = get_embedding(text)
    return store_event(collection, payload, embedding)


# ── scroll (non-semantic, for analytics) ─────────────────────────────

def scroll_all(collection: str, limit: int = 100) -> list[dict]:
    """Scroll all points from a collection (no query vector, payload only).

    Useful for analytics, aggregation, and audit — not for semantic search.
    """
    if not _HAVE_REQUESTS:
        return []
    try:
        body = {"limit": limit, "with_payload": True, "with_vector": False}
        resp = _req.post(
            f"{QDRANT_HOST}/collections/{collection}/points/scroll",
            json=body,
            timeout=5,
        )
        if resp.status_code == 200:
            points = resp.json().get("result", {}).get("points", [])
            return [
                {
                    "id": p["id"],
                    "payload": p.get("payload", {}),
                }
                for p in points
            ]
    except Exception:
        pass
    return []


def scroll_filtered(collection: str, filter_cond: dict, limit: int = 100) -> list[dict]:
    """Scroll points with a Qdrant filter condition."""
    if not _HAVE_REQUESTS:
        return []
    try:
        body = {
            "filter": filter_cond,
            "limit": limit,
            "with_payload": True,
            "with_vector": False,
        }
        resp = _req.post(
            f"{QDRANT_HOST}/collections/{collection}/points/scroll",
            json=body,
            timeout=5,
        )
        if resp.status_code == 200:
            points = resp.json().get("result", {}).get("points", [])
            return [
                {
                    "id": p["id"],
                    "payload": p.get("payload", {}),
                }
                for p in points
            ]
    except Exception:
        pass
    return []


# ── search ────────────────────────────────────────────────────────────

def search_collection(collection: str, query_text: str, limit: int = 5, threshold: float = 0.0) -> list[dict]:
    """Semantic search across a Qdrant collection."""
    if not _HAVE_REQUESTS:
        return []
    embedding = get_embedding(query_text)
    if not embedding:
        return []
    try:
        body = {
            "vector": embedding,
            "limit": limit,
            "with_payload": True,
            "score_threshold": threshold,
        }
        resp = _req.post(
            f"{QDRANT_HOST}/collections/{collection}/points/search",
            json=body,
            timeout=5,
        )
        if resp.status_code == 200:
            results = resp.json().get("result", [])
            return [
                {
                    "score": r["score"],
                    "payload": r.get("payload", {}),
                }
                for r in results
            ]
    except Exception:
        pass
    return []


def recall(query_text: str, limit: int = 3, threshold: float = 0.0) -> list[dict]:
    """Cross-collection cognitive recall.

    Searches routing_history, cognitive_history, and incidents.
    Returns top results across all collections with collection name.
    """
    results = []
    for coll in ("routing_history", "cognitive_history", "incidents"):
        hits = search_collection(coll, query_text, limit=limit, threshold=threshold)
        for h in hits:
            h["collection"] = coll
            results.append(h)
    results.sort(key=lambda x: x["score"], reverse=True)
    return results[:limit]


# ── maintenance ───────────────────────────────────────────────────────

def count_points(collection: str) -> int:
    """Get point count for a collection."""
    info = _qdrant_get(f"/collections/{collection}")
    if info:
        try:
            return info["result"]["points_count"]
        except (KeyError, TypeError):
            pass
    return 0


def prune_collection(collection: str) -> int:
    """Remove points older than retention_days. Returns count removed."""
    cfg = COLLECTION_CONFIGS.get(collection)
    if not cfg or not cfg.get("retention_days"):
        return 0
    if not _HAVE_REQUESTS:
        return 0

    cutoff = time.time() - cfg["retention_days"] * 86400
    try:
        # Scroll points older than cutoff
        filter_body = {
            "filter": {
                "must": [
                    {"key": "timestamp", "range": {"lt": cutoff}}
                ]
            },
            "limit": 100,
            "with_payload": False,
        }
        resp = _req.post(
            f"{QDRANT_HOST}/collections/{collection}/points/scroll",
            json=filter_body,
            timeout=5,
        )
        if resp.status_code != 200:
            return 0
        points = resp.json().get("result", {}).get("points", [])
        if not points:
            return 0
        ids = [p["id"] for p in points]
        delete_body = {"points": ids}
        _req.post(
            f"{QDRANT_HOST}/collections/{collection}/points/delete",
            json=delete_body,
            timeout=5,
        )
        return len(ids)
    except Exception:
        pass
    return 0
