from __future__ import annotations

from enum import Enum


class RuntimeErrorCategory(str, Enum):
    UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
    UPSTREAM_CONNECTION = "UPSTREAM_CONNECTION"
    UPSTREAM_INVALID_RESPONSE = "UPSTREAM_INVALID_RESPONSE"
    LMSTUDIO_TIMEOUT = "LMSTUDIO_TIMEOUT"
    LMSTUDIO_STREAM_STALL = "LMSTUDIO_STREAM_STALL"
    LMSTUDIO_MODEL_UNAVAILABLE = "LMSTUDIO_MODEL_UNAVAILABLE"
    STREAM_INTERRUPTED = "STREAM_INTERRUPTED"
    STREAM_BACKPRESSURE = "STREAM_BACKPRESSURE"
    CLIENT_DISCONNECT = "CLIENT_DISCONNECT"
    REQUEST_VALIDATION = "REQUEST_VALIDATION"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    PROMPT_POLICY = "PROMPT_POLICY"
    PROMPT_SANITIZATION = "PROMPT_SANITIZATION"
    GOVERNANCE_BLOCK = "GOVERNANCE_BLOCK"
    TOOL_VALIDATION = "TOOL_VALIDATION"
    TOOL_MALFORMED = "TOOL_MALFORMED"
    TOOL_PARALLEL_UNSUPPORTED = "TOOL_PARALLEL_UNSUPPORTED"
    WORKFLOW_INVALID_STATE = "WORKFLOW_INVALID_STATE"
    EXECUTOR_READONLY_BLOCK = "EXECUTOR_READONLY_BLOCK"
    SANDBOX_POLICY_BLOCK = "SANDBOX_POLICY_BLOCK"
    SANDBOX_TRAVERSAL_ATTEMPT = "SANDBOX_TRAVERSAL_ATTEMPT"
    ROLLBACK_FAILURE = "ROLLBACK_FAILURE"
    MEMORY_RECALL_FAILURE = "MEMORY_RECALL_FAILURE"
    MEMORY_EMPTY = "MEMORY_EMPTY"
    ROUTING_FAILURE = "ROUTING_FAILURE"
    MODEL_DISABLED = "MODEL_DISABLED"
    CONCURRENCY_THROTTLE = "CONCURRENCY_THROTTLE"
    GPU_PRESSURE = "GPU_PRESSURE"
    VRAM_PRESSURE = "VRAM_PRESSURE"
    GATEWAY_INTERNAL = "GATEWAY_INTERNAL"
    COMPLETION_TRUNCATED = "COMPLETION_TRUNCATED"
    UNKNOWN = "UNKNOWN"


ALL_CATEGORIES: frozenset[str] = frozenset(e.value for e in RuntimeErrorCategory)
