"""FASE OBS-31A: Observability Source-of-Truth Audit.

Converts Prometheus + Loki + Grafana into a fully validated,
coherent operational truth plane aligned with AI-LAB cognitive runtime.
"""

from runtime.observability.contracts import (
    OBSERVABILITY_CONTRACT_VERSION,
    build_observability_source_contract,
    build_dashboard_contract,
    build_metric_contract,
    build_datasource_contract,
    build_grafana_alignment_contract,
    GrafanaAlignmentContract,
)
from runtime.observability.prometheus_audit import (
    PrometheusTargetStatus,
    TargetHealth,
    FreshnessLevel,
    _KNOWN_TARGETS,
    audit_prometheus_targets,
    classify_scrape_target,
    build_prometheus_audit_summary,
    run_prometheus_authority_audit,
    check_critical_metrics,
    calculate_freshness,
    detect_duplicate_jobs,
    fetch_prometheus_targets,
    PROMETHEUS_AUDIT_CONTRACT_VERSION,
)
from runtime.observability.dashboard_validator import (
    DashboardHealth,
    DashboardValidationResult,
    DashboardValidator,
)
from runtime.observability.drift_detector import (
    DriftDetectionResult,
    DriftDetector,
    build_drift_summary,
    build_runtime_alignment_summary,
)
from runtime.observability.grafana_inventory import (
    DashboardHealth as InventoryDashboardHealth,
    build_dashboard_inventory,
    build_inventory_summary,
    classify_dashboard_health,
    get_dashboard_by_uid,
    get_dashboards_by_domain,
    get_dashboards_by_owner,
)
from runtime.observability.runtime_alignment import (
    RUNTIME_ALIGNMENT_CONTRACT_VERSION,
    AlignmentCheck,
    RuntimeAlignmentValidationResult,
    RuntimeAlignmentValidator,
    build_runtime_alignment_result,
)
from runtime.observability.loki_audit import (
    LokiStreamStatus,
    audit_loki,
    build_loki_audit_summary,
)
from runtime.observability.remediation_contracts import (
    REMEDIATION_CONTRACT_VERSION,
    RemediationSeverity,
    ProblemClass,
    RemediationPhase,
    RemediationRisk,
    RemediationItem,
    RemediationPlan,
    RemediationSummary,
    build_remediation_item,
)
from runtime.observability.remediation_planner import (
    REMEDIATION_PLANNER_CONTRACT_VERSION,
    RemediationPlanner,
    build_remediation_plan,
    classify_remediation_priority,
)
from runtime.observability.remediation_executor import (
    EXECUTOR_CONTRACT_VERSION,
    ExecutionResult,
    RemediationExecutor,
    build_manual_execution_guide,
)
from runtime.observability.metric_inventory import (
    MetricEntry,
    MetricCriticality,
    build_metric_inventory,
    build_observability_health_score,
)
from runtime.observability.grafana_semantic_validator import (
    GRAFANA_SEMANTIC_CONTRACT_VERSION,
    build_dashboard_inventory_32b,
    build_grafana_semantic_summary,
    calculate_grafana_alignment_score,
    detect_fake_gpu_panels,
    detect_stale_panels,
    detect_orphan_datasources,
    detect_metric_drift,
    detect_topology_dashboard_alignment,
)

__all__ = [
    "OBSERVABILITY_CONTRACT_VERSION",
    "build_observability_source_contract",
    "build_dashboard_contract",
    "build_metric_contract",
    "build_datasource_contract",
    "build_grafana_alignment_contract",
    "GrafanaAlignmentContract",
    "PrometheusTargetStatus",
    "audit_prometheus_targets",
    "classify_scrape_target",
    "build_prometheus_audit_summary",
    "DashboardHealth",
    "DashboardValidationResult",
    "DashboardValidator",
    "DriftDetectionResult",
    "DriftDetector",
    "build_drift_summary",
    "build_runtime_alignment_summary",
    "InventoryDashboardHealth",
    "build_dashboard_inventory",
    "build_inventory_summary",
    "classify_dashboard_health",
    "get_dashboard_by_uid",
    "get_dashboards_by_domain",
    "get_dashboards_by_owner",
    "GRAFANA_SEMANTIC_CONTRACT_VERSION",
    "build_dashboard_inventory_32b",
    "build_grafana_semantic_summary",
    "calculate_grafana_alignment_score",
    "detect_fake_gpu_panels",
    "detect_stale_panels",
    "detect_orphan_datasources",
    "detect_metric_drift",
    "detect_topology_dashboard_alignment",
    "LokiStreamStatus",
    "audit_loki",
    "build_loki_audit_summary",
    "MetricEntry",
    "MetricCriticality",
    "build_metric_inventory",
    "build_observability_health_score",
    "RUNTIME_ALIGNMENT_CONTRACT_VERSION",
    "AlignmentCheck",
    "RuntimeAlignmentValidationResult",
    "RuntimeAlignmentValidator",
    "build_runtime_alignment_result",
    "REMEDIATION_CONTRACT_VERSION",
    "RemediationSeverity",
    "ProblemClass",
    "RemediationPhase",
    "RemediationRisk",
    "RemediationItem",
    "RemediationPlan",
    "RemediationSummary",
    "build_remediation_item",
    "REMEDIATION_PLANNER_CONTRACT_VERSION",
    "RemediationPlanner",
    "build_remediation_plan",
    "classify_remediation_priority",
    "EXECUTOR_CONTRACT_VERSION",
    "ExecutionResult",
    "RemediationExecutor",
    "build_manual_execution_guide",
]
