server {
    listen 80;
    server_name skills-amd-multi.labrazahome.es;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Standard MIME types are handled by the main nginx.conf including mime.types
}
